---
- name: restart zabbix-server
  service: >
    name=zabbix-server
    state=restarted

- name: reload httpd
  service: >
    name=httpd
    state=reloaded

- name: install cpan modules
  shell: >
    /usr/local/bin/cpanm --installdeps -L local .
    chdir=/usr/lib/zabbix/externalscripts
